# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: Windows-64
name: DP-TPU
dependencies:
  - python=3.10
  - pip=23.3.1
  - setuptools=68.0.0
  - wheel=0.41.2
  - pip:
      - build==1.0.3
      - click==8.1.7
      - colorama==0.4.6
      - numpy==1.26.2
      - opencv-python==4.8.1.78
      - packaging==23.2
      - pandas==2.1.3
      - pip-tools==7.3.0
      - pyproject-hooks==1.0.0
      - python-dateutil==2.8.2
      - pytz==2023.3.post1
      - scipy==1.11.4
      - six==1.16.0
      - tomli==2.0.1
      - tzdata==2023.3

